"""init

Revision ID: create_user_table
Revises: 
Create Date: 2024-10-23

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'create_backend'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('UserID', sa.VARCHAR(length=255), nullable=False),
        sa.Column('Username', sa.VARCHAR(length=255), nullable=False),
        sa.Column('Email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('Password', sa.VARCHAR(length=255), nullable=False),
        sa.Column('ProfileImage', sa.LargeBinary(), nullable=True),  # BLOB for storing images
        sa.Column('About', sa.Text(), nullable=True),
        sa.Column('Skills', sa.Text(), nullable=True),
        sa.Column('Links', sa.VARCHAR(length=255), nullable=True),
        sa.PrimaryKeyConstraint('UserID'),
        sa.UniqueConstraint('Email')
    ) 
    op.create_table(
        'posts',
        sa.Column('PostID', sa.VARCHAR(length=255), nullable=False),
        sa.Column('UserID', sa.VARCHAR(length=255), nullable=False),  # Foreign key
        sa.Column('PostName', sa.TEXT(), nullable=False),
        sa.Column('Description', sa.VARCHAR(length=255), nullable=True),
        sa.Column('MemberNames', sa.VARCHAR(length=255), nullable=True),
        sa.Column('IsOpen', sa.Boolean(), nullable=False),
        sa.Column('Links', sa.VARCHAR(length=255), nullable=True), 
        sa.Column('Tags', sa.VARCHAR(length=255), nullable=True),  
        sa.Column('MoreInfo', sa.VARCHAR(length=255), nullable=True),  
        sa.Column('MoreContactInfo', sa.VARCHAR(length=255), nullable=True),  
        sa.PrimaryKeyConstraint('PostID')
    )
    op.create_table(
        'bookmark',
        sa.Column('PostID', sa.VARCHAR(length=255), nullable=False),
        sa.Column('UserID', sa.VARCHAR(length=255), nullable=False),
        sa.Column('Timestamp', sa.TIMESTAMP(), nullable=False),  
        sa.PrimaryKeyConstraint('PostID', 'UserID')
    )
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('post')
    op.drop_table('bookmark')
    # ### end Alembic commands ###
